<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="8" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="267" started-at="2017-06-30T10:12:46Z" finished-at="2017-06-30T10:12:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="267" started-at="2017-06-30T10:12:46Z" finished-at="2017-06-30T10:12:47Z">
      <class name="com.qainfotech.tap.training.snl.api.BoardTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="beforeTest" is-config="true" duration-ms="27" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="23" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="deletePlayer()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="deletePlayer" duration-ms="7" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePlayer -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="16" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="deletePlayer_NoUserWithSuchUUIDException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="deletePlayer_NoUserWithSuchUUIDException" duration-ms="2" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <exception class="com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '6dc80cdf-b40d-4e72-9f30-a45e0d20c3d4' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException: No Player with uuid '6dc80cdf-b40d-4e72-9f30-a45e0d20c3d4' on board
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:111)
	at com.qainfotech.tap.training.snl.api.BoardTest.deletePlayer_NoUserWithSuchUUIDException(BoardTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePlayer_NoUserWithSuchUUIDException -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="17" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="registerPlayer()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="registerPlayer" duration-ms="11" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayer -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="14" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="registerPlayer_MaxPlayersReachedExeption()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="registerPlayer_MaxPlayersReachedExeption" duration-ms="7" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:68)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayer_MaxPlayersReachedExeption(BoardTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayer_MaxPlayersReachedExeption -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="13" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="registerPlayer_PlayerExistsException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="registerPlayer_PlayerExistsException" duration-ms="1" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'Pranjali' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'Pranjali' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:73)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayer_PlayerExistsException(BoardTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayer_PlayerExistsException -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="10" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="registerplayer_GameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="registerplayer_GameInProgressException" duration-ms="10" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:46Z">
          <exception class="com.qainfotech.tap.training.snl.api.GameInProgressException">
            <message>
              <![CDATA[New player cannot join since the game has started]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.GameInProgressException: New player cannot join since the game has started
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:76)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerplayer_GameInProgressException(BoardTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.GameInProgressException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerplayer_GameInProgressException -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="15" started-at="2017-06-30T15:42:46Z" finished-at="2017-06-30T15:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="rollDice()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="rollDice" duration-ms="5" started-at="2017-06-30T15:42:47Z" finished-at="2017-06-30T15:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDice -->
        <test-method status="PASS" signature="initial()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="initial" is-config="true" duration-ms="14" started-at="2017-06-30T15:42:47Z" finished-at="2017-06-30T15:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initial -->
        <test-method status="PASS" signature="rollDie_InvalidTurnException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@6a2bcfcb]" name="rollDie_InvalidTurnException" duration-ms="4" started-at="2017-06-30T15:42:47Z" finished-at="2017-06-30T15:42:47Z">
          <exception class="com.qainfotech.tap.training.snl.api.InvalidTurnException">
            <message>
              <![CDATA[Player '6dc80cdf-b40d-4e72-9f30-a45e0d20c3d4' does not have the turn]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.InvalidTurnException: Player '6dc80cdf-b40d-4e72-9f30-a45e0d20c3d4' does not have the turn
	at com.qainfotech.tap.training.snl.api.Board.rollDice(Board.java:165)
	at com.qainfotech.tap.training.snl.api.BoardTest.rollDie_InvalidTurnException(BoardTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.InvalidTurnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDie_InvalidTurnException -->
      </class> <!-- com.qainfotech.tap.training.snl.api.BoardTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
